### ISSUE TITLE
Druid 版本太低无法兼容datetime 和 localDateTime 之间的映射， 是否提供了某种方式单独升级druid 的版本

### ISSUE THREAD

**Issue by CodeMokee** [stylefeng/Guns#96]

**Comment by CodeMokee** [comment]
`
org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'createdAt' from result set.  Cause: java.sql.SQLFeatureNotSupportedException
; null; nested exception is java.sql.SQLFeatureNotSupportedException
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:96)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy88.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy108.selectById(Unknown Source)
	at cn.stylefeng.guns.modular.service.impl.CustomerServiceImpl.get(CustomerServiceImpl.java:29)
	at cn.stylefeng.guns.modular.service.impl.CustomerServiceImpl$$FastClassBySpringCGLIB$$a9069cd9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
`

**Comment by CodeMokee** [comment]
So sorry about that. We just need to define a new dependency to override the old one that could detected new version of druid.
